language: perl

perl:
  - "5.22"
  - "5.18"
  - "5.12"

## Template from: https://github.com/FelixKrueger/TrimGalore/blob/master/.travis.yml

install:
  # Install conda + bioconda
  - wget https://repo.anaconda.com/miniconda/Miniconda2-latest-Linux-x86_64.sh
  - bash Miniconda2-latest-Linux-x86_64.sh -b
  - export PATH="$HOME/miniconda2/bin:$PATH"
  #- hash -r
  #- conda config --set always_yes yes --set changeps1 no
  - conda config --add channels bioconda
  - conda config --add channels anaconda
  - conda config --add channels conda-forge
  - conda config --add channels r
  - conda -V  

  #- conda update -q conda
  #- conda install anaconda-client
  #- conda update -q conda
  #- conda info -a
  # Create environment with `requirement.tt`
  - cat /proc/version

  #- conda create -y -q -n test-environment --file requirement.txt 
  #- source activate test-environment
  #- cpanm --force Complete::Util
  #- cpanm Getopt::Long::Subcommand

  - conda install -y -c bioconda r-pheatmap
  - conda install -y -c r r-ggplot2
  - conda install -y -c r r-reshape2
  - conda install -y -c conda-forge r-cowplot
  - conda install -y -c bioconda perl-bio-db-hts
  - conda install -y -c bioconda perl-bioperl
  - cpanm Getopt::Long::Subcommand

script:
  - /ViewBS MethLevDist --sample test_data/test_WT.tab.gz,WT
