language: perl

perl:
  - "5.22"
  - "5.18"
  - "5.12"

## Template from: https://github.com/FelixKrueger/TrimGalore/blob/master/.travis.yml

install:
  # Install conda + bioconda
  - wget https://repo.continuum.io/miniconda/Miniconda-latest-Linux-x86_64.sh -O miniconda.sh;
  - bash miniconda.sh -b -p $HOME/miniconda
  - export PATH="$HOME/miniconda/bin:$PATH"
  - hash -r
  - conda config --set always_yes yes --set changeps1 no
  - conda config --add channels bioconda
  - conda update -q conda
  - conda info -a
  # Create environment with `requirement.txt`
  - conda create -q -n test-environment --file requirement.txt 
  - source activate test-environment
  - cpanm Getopt::Long::Subcommand

script:
  - /ViewBS MethLevDist --sample test_data/test_WT.tab.gz,WT
