language: perl

perl:
  - "5.22"
  - "5.18"
  - "5.12"

## Template from: https://github.com/FelixKrueger/TrimGalore/blob/master/.travis.yml

install:
  # Install conda + bioconda
  - wget https://repo.anaconda.com/miniconda/Miniconda2-latest-Linux-x86_64.sh
  - bash Miniconda2-latest-Linux-x86_64.sh -b
  - export PATH="$HOME/miniconda2/bin:$PATH"
  - hash -r
  - conda config --set always_yes yes --set changeps1 no
  - conda config --set anaconda_upload yes
  - conda config --add channels bioconda
  - conda config --add channels anaconda
  - conda config --add channels conda-forge
  - conda config --add channels r
  - conda -V  

  #- conda update -q conda
  #- conda install anaconda-client
  #- conda update -q conda
  #- conda info -a
  # Create environment with `requirement.tt`
  - cat /proc/version

  - conda env create --name test-environment --file environment.yaml 
  - source activate test-environment
  #- cpanm --force Complete::Util
  - cpanm Getopt::Long::Subcommand
  - conda config --set anaconda_upload yes

script:
  - ./ViewBS MethLevDist --sample data/test_data/test_WT.tab.gz,WT

after_success:
  - test $TRAVIS_BRANCH = "master" && conda install conda-build && conda install anaconda-clienti &&  bash conda/conda_upload.sh


