name: env_ViewBS
channels:
  - bioconda
  - conda-forge
  - defaults
  - r
dependencies:
  - _r-mutex
  - aioeasywebdav
  - aiohttp
  - appdirs
  - asn1crypto
  - async-timeout
  - attrs
  - bcrypt
  - binutils_impl_linux-64
  - binutils_linux-64
  - boto3
  - botocore
  - bwidget
  - bzip2
  - ca-certificates
  - cachetools
  - cairo
  - certifi
  - cffi
  - chardet
  - configargparse
  - cryptography
  - curl
  - datrie
  - decorator
  - docutils
  - dropbox
  - expat
  - filechunkio
  - fontconfig
  - freetype
  - fribidi
  - ftputil
  - gcc_impl_linux-64
  - gcc_linux-64
  - gettext
  - gfortran_impl_linux-64
  - gfortran_linux-64
  - giflib
  - gitdb2
  - gitpython
  - glib
  - google-api-core
  - google-auth
  - google-cloud-core
  - google-cloud-storage
  - google-resumable-media
  - googleapis-common-protos
  - graphite2
  - graphviz
  - gsl
  - gxx_impl_linux-64
  - gxx_linux-64
  - harfbuzz
  - htslib
  - icu
  - idna
  - idna_ssl
  - jinja2
  - jmespath
  - jpeg
  - jsonschema
  - krb5
  - libblas
  - libcblas
  - libcurl
  - libdb
  - libdeflate
  - libedit
  - libffi
  - libgcc
  - libgcc-ng
  - libgd
  - libgfortran-ng
  - libiconv
  - liblapack
  - libpng
  - libprotobuf
  - libssh2
  - libstdcxx-ng
  - libtiff
  - libuuid
  - libwebp
  - libxcb
  - libxml2
  - libxslt
  - make
  - markupsafe
  - multidict
  - ncurses
  - networkx
  - numpy
  - openblas
  - openssl
  - pandas
  - pango
  - paramiko
  - pcre
  - perl
  - perl-aceperl
  - perl-algorithm-munkres
  - perl-app-cpanminus
  - perl-appconfig
  - perl-array-compare
  - perl-bio-asn1-entrezgene
  - perl-bio-db-hts
  - perl-bio-featureio
  - perl-bio-phylo
  - perl-bio-samtools
  - perl-bioperl
  - perl-bioperl-core
  - perl-bioperl-run
  - perl-cgi
  - perl-class-inspector
  - perl-class-method-modifiers
  - perl-clone
  - perl-common-sense
  - perl-convert-binary-c
  - perl-convert-binhex
  - perl-crypt-rc4
  - perl-data-stag
  - perl-db-file
  - perl-dbd-sqlite
  - perl-dbi
  - perl-devel-globaldestruction
  - perl-digest-hmac
  - perl-digest-perl-md5
  - perl-email-date-format
  - perl-encode-locale
  - perl-error
  - perl-exporter-tiny
  - perl-file-listing
  - perl-file-slurp-tiny
  - perl-file-sort
  - perl-file-which
  - perl-font-afm
  - perl-gd
  - perl-graph
  - perl-graphviz
  - perl-html-element-extended
  - perl-html-entities-numbered
  - perl-html-formatter
  - perl-html-parser
  - perl-html-tableextract
  - perl-html-tagset
  - perl-html-tidy
  - perl-html-tree
  - perl-html-treebuilder-xpath
  - perl-http-cookies
  - perl-http-daemon
  - perl-http-date
  - perl-http-message
  - perl-http-negotiate
  - perl-image-info
  - perl-image-size
  - perl-io-html
  - perl-io-sessiondata
  - perl-io-socket-ssl
  - perl-io-string
  - perl-io-stringy
  - perl-io-tty
  - perl-ipc-run
  - perl-jcode
  - perl-json
  - perl-json-xs
  - perl-libwww-perl
  - perl-libxml-perl
  - perl-list-moreutils
  - perl-lwp-mediatypes
  - perl-lwp-protocol-https
  - perl-lwp-simple
  - perl-mailtools
  - perl-math-cdf
  - perl-math-derivative
  - perl-math-random
  - perl-math-spline
  - perl-mime-base64
  - perl-mime-lite
  - perl-mime-tools
  - perl-mime-types
  - perl-mldbm
  - perl-module-runtime
  - perl-moo
  - perl-net-http
  - perl-net-ssleay
  - perl-ntlm
  - perl-ole-storage_lite
  - perl-parse-recdescent
  - perl-pdf-api2
  - perl-postscript
  - perl-role-tiny
  - perl-set-scalar
  - perl-soap-lite
  - perl-sort-naturally
  - perl-spreadsheet-parseexcel
  - perl-spreadsheet-writeexcel
  - perl-statistics-descriptive
  - perl-sub-exporter-progressive
  - perl-svg
  - perl-svg-graph
  - perl-task-weaken
  - perl-template-toolkit
  - perl-test-leaktrace
  - perl-test-more
  - perl-test-pod
  - perl-threaded
  - perl-tie-ixhash
  - perl-timedate
  - perl-tree-dag_node
  - perl-type-tiny
  - perl-unicode-map
  - perl-uri
  - perl-www-robotrules
  - perl-xml-dom
  - perl-xml-dom-xpath
  - perl-xml-filter-buffertext
  - perl-xml-libxml
  - perl-xml-libxslt
  - perl-xml-namespacesupport
  - perl-xml-parser
  - perl-xml-regexp
  - perl-xml-sax
  - perl-xml-sax-base
  - perl-xml-sax-expat
  - perl-xml-sax-writer
  - perl-xml-simple
  - perl-xml-twig
  - perl-xml-writer
  - perl-xml-xpath
  - perl-xml-xpathengine
  - perl-xsloader
  - perl-yaml
  - pip
  - pixman
  - prettytable
  - protobuf
  - psutil
  - pthread-stubs
  - pyasn1
  - pyasn1-modules
  - pycparser
  - pygraphviz
  - pynacl
  - pyrsistent
  - pysftp
  - python
  - python-dateutil
  - python-irodsclient
  - pytz
  - pyyaml
  - r-assertthat
  - r-base
  - r-cli
  - r-colorspace
  - r-crayon
  - r-digest
  - r-fansi
  - r-ggplot2
  - r-ggsci
  - r-glue
  - r-gtable
  - r-labeling
  - r-lazyeval
  - r-magrittr
  - r-mass
  - r-munsell
  - r-pillar
  - r-pkgconfig
  - r-plyr
  - r-r6
  - r-rcolorbrewer
  - r-rcpp
  - r-reshape2
  - r-rlang
  - r-scales
  - r-stringi
  - r-stringr
  - r-tibble
  - r-utf8
  - r-viridislite
  - ratelimiter
  - readline
  - requests
  - rsa
  - s3transfer
  - setuptools
  - six
  - smmap2
  - snakemake
  - snakemake-minimal
  - sqlite
  - tidyp
  - tk
  - tktable
  - typing_extensions
  - urllib3
  - wheel
  - wrapt
  - xmlrunner
  - xorg-libxau
  - xorg-libxdmcp
  - xz
  - yaml
  - yarl
  - zlib

